services:
  - type: web
    name: sherlok-bot
    env: python
    plan: free
    branch: main
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: "3.11.8"